/**: # namespace and node name (double stars means 'ignore')
  ros__parameters:
    localization_split: 1
    localization_proc_time_mean: 4
    localization_proc_time_std: 2
    localization_pre_time_mean: 1
    localization_pre_time_std: 0.2
    localization_wait_time_mean: 1
    localization_wait_time_std: 0.2
    localization_post_time_mean: 1
    localization_post_time_std: 0.2
