/**: # namespace and node name (double stars means 'ignore')
  ros__parameters:
    localization_split: 1
    localization_proc_time_mean: 0.02
    localization_proc_time_std: 0.002
    localization_pre_time_mean: 0.01
    localization_pre_time_std: 0.001
    localization_wait_time_mean: 0.01
    localization_wait_time_std: 0.001
    localization_post_time_mean: 0.01
    localization_post_time_std: 0.001
