/**: # namespace and node name (double stars means 'ignore')
  ros__parameters:
    control_split: 1
    control_proc_time_mean: 4
    control_proc_time_std: 2
    control_pre_time_mean: 1
    control_pre_time_std: 0.2
    control_wait_time_mean: 1
    control_wait_time_std: 0.2
    control_post_time_mean: 1
    control_post_time_std: 0.2