/**: # namespace and node name (double stars means 'ignore')
  ros__parameters:
    control_split: 1
    control_proc_time_mean: 0.02
    control_proc_time_std: 0.002
    control_pre_time_mean: 0.01
    control_pre_time_std: 0.001
    control_wait_time_mean: 0.01
    control_wait_time_std: 0.001
    control_post_time_mean: 0.01
    control_post_time_std: 0.001
